# Generated by Django 3.2.9 on 2021-11-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('nif', models.CharField(default='', max_length=15)),
                ('nivelAcesso', models.IntegerField(max_length=2)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
