# Generated by Django 3.2.9 on 2021-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nivelAcesso',
            field=models.CharField(max_length=2),
        ),
    ]
