# Generated by Django 3.2.9 on 2021-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='qtd_frm_preenchidos',
            field=models.IntegerField(default=0),
        ),
    ]
