# Generated by Django 3.2.9 on 2021-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='totalAlunos',
            field=models.IntegerField(default=0),
        ),
    ]
