# Generated by Django 3.2.9 on 2021-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='', max_length=10)),
                ('pergunta', models.CharField(max_length=200)),
            ],
        ),
    ]
