# Generated by Django 3.2.4 on 2021-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('ra', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
