# Generated by Django 3.2.9 on 2021-12-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0003_alter_aluno_id'),
        ('satisfacao', '0003_remove_satisfacao_nivel'),
        ('turma', '0002_alter_turma_id'),
        ('pergunta', '0002_remove_perguntas_numero'),
        ('envio', '0001_initial'),
        ('importancia', '0003_remove_importancia_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, default='', max_length=500)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_aluno', to='aluno.aluno')),
                ('id_importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_importancia', to='importancia.importancia')),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pergunta', to='pergunta.perguntas')),
                ('id_satisfacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_satisfacao', to='satisfacao.satisfacao')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_turma_form', to='turma.turma')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_envio', to='envio.envio')),
            ],
        ),
    ]
