# Generated by Django 3.2.4 on 2021-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_formulario_id_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
