# Generated by Django 4.0 on 2021-12-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_formulario_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='ano',
        ),
    ]
