# Generated by Django 3.2.9 on 2021-11-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfacao',
            name='desc',
            field=models.CharField(default='', max_length=15),
        ),
    ]
