# Generated by Django 3.2.4 on 2021-12-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfacao', '0002_satisfacao_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfacao',
            name='nivel',
        ),
    ]
