# Generated by Django 3.2.9 on 2021-11-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(default='', max_length=2)),
                ('ano', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
